apiVersion: v1
kind: Pod
metadata:
  name: guido-nginx-nfs-pod 
  labels:
    name: nginx-nfs-pod
    app: guido-nginx
spec:
  containers:
    - name: nginx-nfs-container
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: nfsvol 
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc