apiVersion: v1
kind: Pod
metadata:
  name: guidoapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes from Guido-container! && sleep 3600']